[package]
name = "runescape-wiki-crawler"
version = "0.1.0"
edition = "2024"

[dependencies]
flume = "0.11"
anyhow = "1.0"
tokio = { version = "1.49.0", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"